language: go
sudo: false

env:
  global:
    - GOVET="go vet"
    - GOIMPORTS="goimports"

matrix:
  include:
    - go: "1.13"
    - go: "1.14"
    - go: "1.x"
    - go: "master"
  allow_failures:
    - go: "master"
  fast_finish: true

before_install:
  - go get golang.org/x/tools/cmd/goimports

script:
    - make all && $GOVET . && $GOIMPORTS -l . | grep -v assets | wc -l | grep '0$' && go fix
